[project]
language = "python"
install = ["pip install -r requirements.txt"]
start = "python main.py"

[phases.setup]
packages = ["python3", "python3-pip", "python3-venv"]

[phases.build]
commands = [
    "pip install --no-cache-dir -r requirements.txt"
]

[phases.start]
commands = [
    "python main.py"
]
